name: Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer test
      - name: Code quality (PHPStan)
        run: composer phpstan
      - name: Code style (Laravel Pint)
        run: composer pint:test